GET http://{{host}}:{{port}}{{context-path}}/api/about
#Accept: Application/json

> {%
client.test("Request '/about' executed successfully without authorized user.",function() {
  client.assert((response.status===200),"Response status is not 200.");
})
 %}
