server:
  port: 8585
  servlet:
    context-path: "/v1"
spring:
  application:
    name: tdd_test2_jwt

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_test_users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: false
    properties:
      hibernate.format_sql: true
      # generated statistics
      hibernate.generate_statistics: true
      #catch slow queries
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 3
      #/cashing
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        sql: DEBUG
